title: AngryBanUh - An Anagram of Bryan Huang
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bryan Huang # add your name
author-img: bryan-huang.png # add your photo
about-author: Senior Manager @ AirWallex | Formerly of Autodesk and Dell EMC | Low-end (pronounced [ˈres(t)fəl])  full-stack (pronounced [web]) codesmith who's got no clue what hes doing with JS/.NET/Java/GO/Rust/PHP/Python and the rest of universe... # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: dukedhx # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
